services:
  # Fallback PostgreSQL (use when not using Supabase local)
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: im_reading_here
    ports:
      - "5432:5432"  # Different port from Supabase (54322)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - fallback  # Only start with: docker compose --profile fallback up

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data:
